[2023-12-20 18:12:10,916] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: s3_to_postgres_dag.push_to_postgres manual__2023-12-20T18:12:03.648551+00:00 [queued]>
[2023-12-20 18:12:10,931] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: s3_to_postgres_dag.push_to_postgres manual__2023-12-20T18:12:03.648551+00:00 [queued]>
[2023-12-20 18:12:10,932] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2023-12-20 18:12:10,932] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2023-12-20 18:12:10,933] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2023-12-20 18:12:10,948] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): push_to_postgres> on 2023-12-20 18:12:03.648551+00:00
[2023-12-20 18:12:10,954] {standard_task_runner.py:52} INFO - Started process 3243 to run task
[2023-12-20 18:12:10,959] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 's3_to_postgres_dag', 'push_to_postgres', 'manual__2023-12-20T18:12:03.648551+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpcn1uiaz_', '--error-file', '/tmp/tmpgu5rqj4f']
[2023-12-20 18:12:10,960] {standard_task_runner.py:80} INFO - Job 4: Subtask push_to_postgres
[2023-12-20 18:12:11,040] {logging_mixin.py:109} INFO - Running <TaskInstance: s3_to_postgres_dag.push_to_postgres manual__2023-12-20T18:12:03.648551+00:00 [running]> on host eddfb0464777
[2023-12-20 18:12:11,104] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=s3_to_postgres_dag
AIRFLOW_CTX_TASK_ID=push_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-12-20T18:12:03.648551+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-20T18:12:03.648551+00:00
[2023-12-20 18:12:11,560] {logging_mixin.py:109} INFO - Index(['STORE_ID', 'STORE_LOCATION', 'PRODUCT_CATEGORY', 'PRODUCT_ID', 'MRP',
       'CP', 'DISCOUNT', 'SP', 'Date'],
      dtype='object')
[2023-12-20 18:12:19,565] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/first_dag.py", line 53, in push_to_postgres
    port=5432
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "your_endpoint" to address: Temporary failure in name resolution

[2023-12-20 18:12:19,595] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=s3_to_postgres_dag, task_id=push_to_postgres, execution_date=20231220T181203, start_date=20231220T181210, end_date=20231220T181219
[2023-12-20 18:12:19,613] {standard_task_runner.py:98} ERROR - Failed to execute job 4 for task push_to_postgres (could not translate host name "your_endpoint" to address: Temporary failure in name resolution
; 3243)
[2023-12-20 18:12:19,654] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-12-20 18:12:19,716] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
