[2023-12-20 18:33:11,802] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: s3_to_postgres_dag.push_to_postgres manual__2023-12-20T18:33:06.620816+00:00 [queued]>
[2023-12-20 18:33:11,822] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: s3_to_postgres_dag.push_to_postgres manual__2023-12-20T18:33:06.620816+00:00 [queued]>
[2023-12-20 18:33:11,825] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2023-12-20 18:33:11,828] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2023-12-20 18:33:11,829] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2023-12-20 18:33:11,869] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): push_to_postgres> on 2023-12-20 18:33:06.620816+00:00
[2023-12-20 18:33:11,877] {standard_task_runner.py:52} INFO - Started process 4243 to run task
[2023-12-20 18:33:11,881] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 's3_to_postgres_dag', 'push_to_postgres', 'manual__2023-12-20T18:33:06.620816+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp1wmwtk5g', '--error-file', '/tmp/tmpft43z7h9']
[2023-12-20 18:33:11,883] {standard_task_runner.py:80} INFO - Job 10: Subtask push_to_postgres
[2023-12-20 18:33:11,937] {logging_mixin.py:109} INFO - Running <TaskInstance: s3_to_postgres_dag.push_to_postgres manual__2023-12-20T18:33:06.620816+00:00 [running]> on host eddfb0464777
[2023-12-20 18:33:11,980] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=s3_to_postgres_dag
AIRFLOW_CTX_TASK_ID=push_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-12-20T18:33:06.620816+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-20T18:33:06.620816+00:00
[2023-12-20 18:33:12,376] {logging_mixin.py:109} INFO - Index(['STORE_ID', 'STORE_LOCATION', 'PRODUCT_CATEGORY', 'PRODUCT_ID', 'MRP',
       'CP', 'DISCOUNT', 'SP', 'Date'],
      dtype='object')
[2023-12-20 18:33:20,384] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/first_dag.py", line 53, in push_to_postgres
    port=5432
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "transactionsdb" to address: Temporary failure in name resolution

[2023-12-20 18:33:20,409] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=s3_to_postgres_dag, task_id=push_to_postgres, execution_date=20231220T183306, start_date=20231220T183311, end_date=20231220T183320
[2023-12-20 18:33:20,424] {standard_task_runner.py:98} ERROR - Failed to execute job 10 for task push_to_postgres (could not translate host name "transactionsdb" to address: Temporary failure in name resolution
; 4243)
[2023-12-20 18:33:20,439] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-12-20 18:33:20,469] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
